title: BitCraft
tagline: "Crypto Consulting Cosmonauts"
url: 'https://bitcraft.io'
baseurl: ''

markdown: kramdown
permalink: /posts/:year/:month/:title.html
paginate: 3
paginate_path: /posts/:num
highlighter: rouge

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"